name: Espelhar para Pasta do Cliente

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo original
        uses: actions/checkout@v4
        with:
          path: main-source

      - name: Remover git history (Transformar em pasta comum)
        run: rm -rf main-source/.git

      - name: Push para pasta espec√≠fica do cliente
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_DESTINO }}
        with:
          destination-github-username: 'renovaprime'
          destination-repository-name: 'renovaprime_codigos'
          target-branch: main
          target-directory: 'totaldoctor-front'
          source-directory: 'main-source'
          user-email: ramon@opemcode.com

      - name: Notifica√ß√£o Discord (Sucesso)
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: '‚úÖ A sincroniza√ß√£o com o reposit√≥rio do cliente foi conclu√≠da com sucesso!'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notifica√ß√£o Discord (Falha)
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: 'üö® Falha na sincroniza√ß√£o com o reposit√≥rio do cliente.'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}